version: '3.8'

services:
  swagger-cli:
    container_name: swagger-cli
    build:
      context: ./doc/swagger
      dockerfile: Dockerfile
    volumes:
      - ./doc/swagger:/swagger
  swagger-ui:
    image: swaggerapi/swagger-ui
    depends_on:
      - swagger-cli
    environment:
      SWAGGER_JSON: /openapi.yml
    volumes:
      - ./doc/swagger/openapi.yml:/openapi.yml
    ports:
      - "8080:8080"