name: api build and push to gcp

on:
  workflow_dispatch:

env:
  APP_ENV: dev
  SERVICE_NAME: portfolio-service-api
  PROJECT_ID: template-pj-418409
  REPOSITORY_NAME: dev-gcp-portfolio-repository-api
  REGION: asia-northeast1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4

    - id: "auth"
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - uses: docker/setup-buildx-action@v3

    - name: Build Push to Artifact
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: |
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:latest
