name: Deploy to Cloud Run Frontend

on:
  workflow_dispatch:

env:
  APP_ENV: dev
  SERVICE_NAME: portfolio-service-front
  PROJECT_ID: template-pj-418409
  REPOSITORY_NAME: dev-gcp-portfolio-repository-front
  REGION: asia-northeast1

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image to Artifact Registry
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            asia-northeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
            asia-northeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:latest
          build-args: |
            FIREBASE_API_KEY="${{ secrets.FIREBASE_API_KEY }}"
            FIREBASE_AUTH_DOMAIN="${{ secrets.FIREBASE_AUTH_DOMAIN }}"
            FIREBASE_PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID }}"
            FIREBASE_STORAGE_BUCKET="${{ secrets.FIREBASE_STORAGE_BUCKET }}"
            FIREBASE_MESSAGING_SENDER_ID="${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"
            FIREBASE_APP_ID="${{ secrets.FIREBASE_APP_ID }}"
            API_BASE_URL="${{ secrets.API_BASE_URL }}"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.7.0
        with:
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          region: ${{ env.REGION }}
