name: go-lint

on:
  pull_request:
    branches:
      - develop
      - feature/*

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./backend/go.mod

      - name: Wire
        run: |
          cd backend
          go mod download
          go install github.com/google/wire/cmd/wire@v0.6.0
          go generate -x -tags wireinject ./wire/wire.go

      - name: go-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: ./backend
          reporter: github-pr-review
          level: warning
          fail_on_error: true
          golangci_lint_flags: "--config=.golangci.yml"
          go_version_file: ./backend/go.mod
